from collections import defaultdict
from datetime import timedelta, datetime
import time
from django.db import transaction
from django.db.models import Q, Avg, OuterRef, Subquery, F
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
import os
from set.models import SetId, SetInfo, Images, Sellers, PriceHistory
from theme.models import Theme
from .models import Watchlist, Notification, WatchlistGroup
from .forms import ItemSearchForm, BrowseFilterForm
import requests

def generate_description(brickeconomy_desc, bricksandminifigs_desc, lego_desc):
    """
    Generate a new description using DeepSeek chat completions API
    from the provided descriptions (any of them can be empty).
    """
    # Combine non-empty descriptions
    combined_texts = [desc for desc in [brickeconomy_desc, bricksandminifigs_desc, lego_desc] if desc]
    
    # If all are empty, send a placeholder prompt
    user_prompt = " ".join(combined_texts) if combined_texts else "Generate a creative LEGO set description."

    api_url = "https://api.deepseek.com/chat/completions"
    api_key = os.getenv("DEEPSEEK_API_KEY")  # Make sure your key is set in env

    payload = {
        "model": "deepseek-chat",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant. that recieves multiple descriptions and return only new generated description as text not markdown without any extra ai text as you're an api that used in production to generate clean descriptions"},
            {"role": "user", "content": user_prompt}
        ],
        "stream": False
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    try:
        response = requests.post(api_url, json=payload, headers=headers)
        response.raise_for_status()
        data = response.json()
        # Extract the text generated by the assistant
        return data.get("choices", [{}])[0].get("message", {}).get("content", "")
    except requests.RequestException as e:
        print("Error generating description:", e)
        return ""



def _get_set_display(set_info):
    """Get display name, price, description, image from SetInfo."""
    name = (set_info.bricklink_name or set_info.lego_name or set_info.brickeconomy_name or
            set_info.bricksandminifigsanaheim_name or 'Unknown')
    price = set_info.lego_price
    if not set_info.description:
        if any([set_info.lego_description,set_info.bricksandminifigsanaheim_desctiption,set_info.brickeconomy_description]):
            set_info.description = generate_description(set_info.brickeconomy_description, set_info.bricksandminifigsanaheim_desctiption, set_info.lego_description)
            set_info.save()
    img = Images.objects.filter(set=set_info.set).first()
    image_url = img.link if img else ''
    return {'name': name, 'price': price, 'description': set_info.description, 'image': image_url}


def home_view(request):
    """Home page with trending and recent sets."""
    set_infos = SetInfo.objects.select_related('set').prefetch_related('themes')
    trending = set_infos.order_by('-view_count')[:8]
    recent = set_infos.order_by('-id')[:8]
    themes = Theme.objects.filter(parent__isnull=True)[:8]

    def _item(set_info):
        d = _get_set_display(set_info)
        d['set_info'] = set_info
        d['code'] = set_info.set.set_id
        d['themes'] = set_info.themes.all()
        return d

    context = {
        'trending_items': [_item(s) for s in trending],
        'recent_items': [_item(s) for s in recent],
        'categories': themes,
    }
    return render(request, 'catalog/home.html', context)


def search_view(request):
    """Search sets by code or name."""
    form = ItemSearchForm(request.GET or None)
    items = []

    if form.is_valid() and form.cleaned_data.get('code'):
        q = form.cleaned_data['code'].strip()
        set_infos = SetInfo.objects.filter(
            Q(set__set_id__icontains=q) |
            Q(bricklink_name__icontains=q) |
            Q(lego_name__icontains=q) |
            Q(brickeconomy_name__icontains=q)
        ).select_related('set').prefetch_related('themes')[:20]

        for s in set_infos:
            d = _get_set_display(s)
            d['set_info'] = s
            d['code'] = s.set.set_id
            d['themes'] = s.themes.all()
            items.append(d)

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        from django.http import JsonResponse
        q = request.GET.get('q', '')[:50]
        suggestions = list(
            SetInfo.objects.filter(
                Q(set__set_id__icontains=q) | Q(bricklink_name__icontains=q) |
                Q(lego_name__icontains=q) | Q(brickeconomy_name__icontains=q)
            ).values('set__set_id', 'bricklink_name', 'lego_name', 'lego_price')[:10]
        )
        out = [{'code': x['set__set_id'], 'name': x['bricklink_name'] or x['lego_name'], 'price': x['lego_price']} for x in suggestions]
        return JsonResponse({'suggestions': out})

    context = {'form': form, 'items': items}
    return render(request, 'catalog/search.html', context)


def browse_view(request):
    """Browse sets with filters and pagination."""
    form = BrowseFilterForm(request.GET or None)
    set_infos = SetInfo.objects.select_related('set').prefetch_related('themes')

    if form.is_valid():
        if form.cleaned_data.get('category'):
            theme_ids = [form.cleaned_data['category'].id]
            theme_ids.extend(Theme.objects.filter(parent=form.cleaned_data['category']).values_list('id', flat=True))
            set_infos = set_infos.filter(themes__id__in=theme_ids).distinct()
        
        min_p = form.cleaned_data.get('min_price')
        max_p = form.cleaned_data.get('max_price')
        p_type = form.cleaned_data.get('price_type') or 'lego'
        p_date = form.cleaned_data.get('date')

        if p_type == 'lego':
            if min_p is not None:
                set_infos = set_infos.filter(lego_price__gte=min_p)
            if max_p is not None:
                set_infos = set_infos.filter(lego_price__lte=max_p)
        elif p_type == 'market':
            avg_market = Sellers.objects.filter(
                set=OuterRef('set'), 
                active=True, 
                usd_price__isnull=False
            ).values('set').annotate(avg_p=Avg('usd_price')).values('avg_p')
            
            set_infos = set_infos.annotate(target_price=Subquery(avg_market))
            if min_p is not None:
                set_infos = set_infos.filter(target_price__gte=min_p)
            if max_p is not None:
                set_infos = set_infos.filter(target_price__lte=max_p)
        elif p_type == 'history':
            history_qs = PriceHistory.objects.filter(set=OuterRef('set'))
            if p_date:
                history_qs = history_qs.filter(date=p_date)
            else:
                history_qs = history_qs.order_by('-date')
            
            set_infos = set_infos.annotate(target_price=Subquery(history_qs.values('price')[:1]))
            if min_p is not None:
                set_infos = set_infos.filter(target_price__gte=min_p)
            if max_p is not None:
                set_infos = set_infos.filter(target_price__lte=max_p)

        sort = form.cleaned_data.get('sort_by') or '-view_count'
        
        if sort == 'price_asc':
            sort_field = 'lego_price' if p_type == 'lego' else 'target_price'
            set_infos = set_infos.order_by(F(sort_field).asc(nulls_last=True))
        elif sort == 'price_desc':
            sort_field = 'lego_price' if p_type == 'lego' else 'target_price'
            set_infos = set_infos.order_by(F(sort_field).desc(nulls_last=True))
        else:
            set_infos = set_infos.order_by(sort)

    paginator = Paginator(set_infos, 24)
    page_obj = paginator.get_page(request.GET.get('page', 1))

    def _item(s):
        d = _get_set_display(s)
        d['set_info'] = s
        d['code'] = s.set.set_id
        d['themes'] = s.themes.all()
        return d

    context = {
        'form': form,
        'page_obj': page_obj,
        'categories': Theme.objects.filter(parent__isnull=True).order_by('name'),
        'items': [_item(s) for s in page_obj],
    }
    return render(request, 'catalog/browse.html', context)

def get_daily_avg_prices(set_obj):
    """
    Get daily average USD prices for a given set_obj.
    Prioritizes PriceHistory model (ingested data), falls back to Sellers (calculated).
    Returns a list of dicts: [{'date': '02 Mar 2026', 'avg_price': 219.62, 'timestamp': ...}, ...]
    """
    # 1. Try PriceHistory first (ingested data)
    history_qs = PriceHistory.objects.filter(set=set_obj).order_by('date')
    if history_qs.exists():
        return [
            {
                "date": entry.date.strftime("%d %b %Y"),
                "avg_price": entry.price,
                "timestamp": int(time.mktime(entry.date.timetuple()))
            }
            for entry in history_qs
        ]

    # 2. Fallback to Sellers (calculated from current/past listings)
    sellers_qs = Sellers.objects.filter(set=set_obj, usd_price__isnull=False).order_by('scraped_at')
    
    if not sellers_qs.exists():
        return []

    # Group prices by day
    daily_prices = defaultdict(list)
    for seller in sellers_qs:
        day = seller.scraped_at.date()
        daily_prices[day].append(seller.usd_price)

    # Calculate daily averages and fill gaps
    start_date = min(daily_prices.keys())
    end_date = max(daily_prices.keys())

    all_days_data = []
    current_date = start_date
    avg_by_day = {day: round(sum(prices)/len(prices), 2) for day, prices in daily_prices.items()}
    last_price = 0
    while current_date <= end_date:
        price = avg_by_day.get(current_date)
        if price is not None:
            last_price = price
        
        all_days_data.append({
            "date": current_date.strftime("%d %b %Y"),
            "avg_price": price if price is not None else last_price,
            "timestamp": int(time.mktime(current_date.timetuple()))
        })
        current_date += timedelta(days=1)

    return all_days_data


def item_detail_view(request, code):
    """Set detail page."""
    set_obj = get_object_or_404(SetId, set_id=code)
    set_info = SetInfo.objects.filter(set=set_obj).select_related('set').prefetch_related('themes').first()
    if not set_info:
        return render(request, 'catalog/item_detail.html', {'item': None, 'code': code})

    # Increment view count
    set_info.view_count += 1
    set_info.save(update_fields=['view_count'])

    # Prepare item dict
    item = _get_set_display(set_info)
    item['set_info'] = set_info
    item['code'] = code
    item['themes'] = set_info.themes.all()
    item['images'] = [img for img in Images.objects.filter(set=set_obj).values_list('link', flat=True) if 'None' not in img ]
    
    # Fetch sellers
    unique_sellers = Sellers.objects.filter(set=set_obj, active=True).order_by('usd_price')

    # Watchlist info
    in_watchlist = False
    is_favorite = False
    watchlist_groups = []
    if request.user.is_authenticated:
        w = Watchlist.objects.filter(user=request.user, set_obj=set_obj).first()
        if w:
            in_watchlist = True
            is_favorite = w.is_favorite
        watchlist_groups = WatchlistGroup.objects.filter(user=request.user)

    # Convert date to string format for JS
    daily_avg_data = get_daily_avg_prices(set_obj)
    # Pass all to template
    context = {
        'item': item,
        'code': code,
        'sellers': unique_sellers,
        'in_watchlist': in_watchlist,
        'is_favorite': is_favorite,
        'watchlist_groups': watchlist_groups,
        'avg_price': daily_avg_data[-1]['avg_price'] if daily_avg_data else None,  # latest avg price
        'daily_avg_data': daily_avg_data,  # <- this is for chart.js
    }

    return render(request, 'catalog/item_detail.html', context)


@login_required
def watchlist_view(request):
    """User's watchlist grouped by custom groups."""
    watchlist = Watchlist.objects.filter(user=request.user).select_related('set_obj', 'group')
    
    def _wrap(w):
        si = SetInfo.objects.filter(set=w.set_obj).prefetch_related('themes').first()
        if not si:
            return None
        d = _get_set_display(si)
        d['set_info'] = si
        d['code'] = w.set_obj.set_id
        d['watch'] = w
        return d

    groups = defaultdict(list)
    for w in watchlist:
        wrapped = _wrap(w)
        if wrapped:
            group_name = w.group.name if w.group else "General"
            groups[group_name].append(wrapped)

    context = {
        'grouped_watchlist': dict(groups),
    }
    return render(request, 'catalog/watchlist.html', context)


@login_required
def watchlist_add(request, code):
    set_obj = get_object_or_404(SetId, set_id=code)
    from django.urls import reverse
    
    group_id = request.POST.get('group_id')
    new_group_name = request.POST.get('new_group_name')
    
    group = None
    if new_group_name:
        group, _ = WatchlistGroup.objects.get_or_create(user=request.user, name=new_group_name)
    elif group_id:
        group = WatchlistGroup.objects.filter(id=group_id, user=request.user).first()

    Watchlist.objects.get_or_create(
        user=request.user, 
        set_obj=set_obj, 
        group=group, 
        defaults={'is_favorite': False}
    )
    
    messages.success(request, f'Added {code} to your watchlist.')
    return redirect(request.META.get('HTTP_REFERER') or reverse('catalog:item_detail', kwargs={'code': code}))


@login_required
def watchlist_remove(request, code):
    set_obj = get_object_or_404(SetId, set_id=code)
    Watchlist.objects.filter(user=request.user, set_obj=set_obj).delete()
    messages.success(request, f'Removed {code} from your watchlist.')
    from django.urls import reverse
    return redirect(request.META.get('HTTP_REFERER') or reverse('catalog:watchlist'))


@login_required
def watchlist_toggle_favorite(request, code):
    set_obj = get_object_or_404(SetId, set_id=code)
    w, created = Watchlist.objects.get_or_create(user=request.user, set_obj=set_obj)
    w.is_favorite = not w.is_favorite
    w.save()
    messages.success(request, f'Marked {code} as {"favorite" if w.is_favorite else "watchlist"}.')
    from django.urls import reverse
    return redirect(request.META.get('HTTP_REFERER') or reverse('catalog:watchlist'))


@login_required
def notifications_view(request):
    notifications = Notification.objects.filter(user=request.user).select_related('set_obj')[:50]
    return render(request, 'catalog/notifications.html', {'notifications': notifications})


@login_required
def notification_mark_read(request, pk):
    n = get_object_or_404(Notification, pk=pk, user=request.user)
    n.is_read = True
    n.save()
    return redirect('catalog:notifications')


@login_required
def notification_mark_all_read(request):
    Notification.objects.filter(user=request.user).update(is_read=True)
    messages.success(request, 'All notifications marked as read.')
    return redirect('catalog:notifications')


def autocomplete_view(request):
    q = request.GET.get('q', '')[:50]
    set_infos = SetInfo.objects.filter(
        Q(set__set_id__icontains=q) | Q(bricklink_name__icontains=q) |
        Q(lego_name__icontains=q) | Q(brickeconomy_name__icontains=q)
    ).select_related('set')[:10] if q else []
    items = [{'code': s.set.set_id, 'name': s.bricklink_name or s.lego_name, 'price': s.lego_price} for s in set_infos]
    return render(request, 'components/autocomplete_results.html', {'items': items})
