# Generated by Django 5.2.10 on 2026-01-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10485759, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=10485759, null=True)),
                ('country', models.CharField(blank=True, max_length=10485759, null=True)),
                ('complete', models.CharField(blank=True, max_length=10485759, null=True)),
                ('usd_price', models.FloatField(blank=True, null=True)),
                ('real_price', models.CharField(blank=True, max_length=10485759, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('buy_url', models.URLField(blank=True, max_length=10485759, null=True)),
                ('source', models.CharField(choices=[('brickLink', 'brickLink'), ('brickEconomy', 'brickEconomy')], db_index=True, max_length=10485759)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=10485759)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
            ],
        ),
        migrations.CreateModel(
            name='SetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricklink_name', models.CharField(blank=True, max_length=10485759, null=True)),
                ('lego_name', models.CharField(blank=True, max_length=10485759, null=True)),
                ('brickeconomy_name', models.CharField(blank=True, max_length=10485759, null=True)),
                ('bricksandminifigsanaheim_name', models.CharField(blank=True, max_length=10485759, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('lego_price', models.FloatField(blank=True, null=True)),
                ('brickeconomy_description', models.TextField(blank=True, null=True)),
                ('lego_description', models.TextField(blank=True, null=True)),
                ('bricksandminifigsanaheim_desctiption', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=10485759, null=True)),
                ('dim', models.CharField(blank=True, max_length=10485759, null=True)),
                ('parts', models.CharField(blank=True, max_length=10485759, null=True)),
                ('bricklink_url', models.URLField(blank=True, max_length=10485759, null=True)),
                ('lego_url', models.URLField(blank=True, max_length=10485759, null=True)),
                ('bricksandminifigsanaheim_url', models.URLField(blank=True, max_length=10485759, null=True)),
                ('brickeconomy_url', models.URLField(blank=True, max_length=10485759, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
                ('themes', models.ManyToManyField(to='theme.theme')),
            ],
        ),
    ]
