# Generated by Django 6.0.1 on 2026-01-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete', models.CharField(blank=True, max_length=200, null=True)),
                ('usd_price', models.IntegerField(blank=True, null=True)),
                ('real_price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('buy_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('BrickLink', 'BrickLink'), ('BrickEconomy', 'BrickEconomy')], max_length=200)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
            ],
        ),
        migrations.CreateModel(
            name='SetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricklink_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lego_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brickeconomy_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('brickeconomy_description', models.TextField(blank=True, null=True)),
                ('lego_description', models.TextField(blank=True, null=True)),
                ('bricksandminifigsanaheim_name', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('dim', models.CharField(blank=True, max_length=200, null=True)),
                ('parts', models.CharField(blank=True, max_length=200, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
            ],
        ),
    ]
