# Generated by Django 6.0.1 on 2026-01-21 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setinfo',
            name='bricksandminifigsanaheim_desctiption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setinfo',
            name='lego_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setinfo',
            name='themes',
            field=models.ManyToManyField(to='theme.theme'),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='bricksandminifigsanaheim_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
            ],
        ),
    ]
