# Generated by Django 5.2.10 on 2026-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_setinfo_bricksandminifigsanaheim_desctiption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='source',
            field=models.CharField(choices=[('BrickLink', 'BrickLink'), ('BrickEconomy', 'BrickEconomy')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='setid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setid',
            name='set_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
