# Generated by Django 5.2.10 on 2026-01-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0003_alter_images_id_alter_sellers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
