# Generated by Django 5.2.10 on 2026-01-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0004_alter_sellers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='link',
            field=models.URLField(max_length=900000),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='buy_url',
            field=models.URLField(blank=True, max_length=900000, null=True),
        ),
    ]
