# Generated by Django 5.2.10 on 2026-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_alter_images_link_alter_sellers_buy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='real_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
