# Generated by Django 5.2.10 on 2026-01-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0006_alter_sellers_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='source',
            field=models.CharField(choices=[('brickLink', 'brickLink'), ('brickEconomy', 'brickEconomy')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='usd_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
