# Generated by Django 5.2.10 on 2026-01-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0007_alter_sellers_source_alter_sellers_usd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='setinfo',
            name='brickeconomy_url',
            field=models.URLField(blank=True, max_length=900000, null=True),
        ),
        migrations.AddField(
            model_name='setinfo',
            name='bricklink_url',
            field=models.URLField(blank=True, max_length=900000, null=True),
        ),
        migrations.AddField(
            model_name='setinfo',
            name='bricksandminifigsanaheim_url',
            field=models.URLField(blank=True, max_length=900000, null=True),
        ),
        migrations.AddField(
            model_name='setinfo',
            name='lego_url',
            field=models.URLField(blank=True, max_length=900000, null=True),
        ),
    ]
