# Generated by Django 5.2.10 on 2026-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0008_setinfo_brickeconomy_url_setinfo_bricklink_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='complete',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='condition',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='country',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='name',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='real_price',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='source',
            field=models.CharField(choices=[('brickLink', 'brickLink'), ('brickEconomy', 'brickEconomy')], db_index=True, max_length=99999999),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='brickeconomy_name',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='bricklink_name',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='bricksandminifigsanaheim_name',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='dim',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='lego_name',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='parts',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
    ]
