# Generated by Django 5.2.10 on 2026-02-08 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0012_setinfo_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='scraped_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2026, 2, 8, 3, 8, 3, 232162, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setinfo',
            name='scraped_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2026, 2, 8, 3, 8, 11, 836063, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
