# Generated by Django 5.2.10 on 2026-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0013_sellers_scraped_at_setinfo_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='content',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellers',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
