# Generated by Django 5.2.10 on 2026-03-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0014_images_content_sellers_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='content',
        ),
    ]
