# Generated by Django 5.2.10 on 2026-03-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0015_remove_images_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
