# Generated by Django 5.2.10 on 2026-03-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0016_alter_sellers_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='setinfo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='setinfo',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
