# Generated by Django 5.2.10 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0017_setinfo_description_alter_setinfo_scraped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
