# Generated by Django 5.2.10 on 2026-06-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0018_alter_setinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.FloatField()),
                ('source', models.CharField(default='brickeconomy', max_length=100)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='set.setid')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('set', 'date', 'source')},
            },
        ),
    ]
