# Generated by Django 6.0.6 on 2026-06-21 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_watchlistgroup_alter_watchlist_unique_together_and_more'),
        ('set', '0020_alter_images_id_alter_pricehistory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order within the section.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.homesection')),
                ('set_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.setid')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'set_obj')},
            },
        ),
    ]
