# Generated by Django 6.0.1 on 2026-01-21 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(choices=[('BrickLink', 'BrickLink'), ('BrickEconomy', 'BrickEconomy')], max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme')),
            ],
        ),
    ]
