# Generated by Django 5.2.10 on 2026-01-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4000)),
                ('source', models.CharField(choices=[('brickLink', 'brickLink'), ('brickEconomy', 'brickEconomy'), ('lego', 'lego'), ('bricksandminifigsanaheim', 'bricksandminifigsanaheim')], max_length=4000)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.theme')),
            ],
        ),
    ]
