# Generated by Django 5.2.10 on 2026-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_theme_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='source',
            field=models.CharField(choices=[('bricklink', 'bricklink'), ('brickeconomy', 'brickeconomy'), ('LEGO', 'LEGO'), ('bricksandminifigsanaheim', 'bricksandminifigsanaheim')], max_length=4000),
        ),
    ]
