# Generated by Django 5.2.10 on 2026-01-25 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_theme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.theme'),
        ),
    ]
