# Generated by Django 5.2.10 on 2026-01-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_theme_name_alter_theme_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='source',
            field=models.CharField(choices=[('BrickLink', 'BrickLink'), ('BrickEconomy', 'BrickEconomy'), ('Lego', 'Lego'), ('Bricksandminifigsanaheim', 'Bricksandminifigsanaheim')], max_length=200),
        ),
    ]
