# Generated by Django 5.2.10 on 2026-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_theme_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='source',
            field=models.CharField(choices=[('brickLink', 'brickLink'), ('brickEconomy', 'brickEconomy'), ('lego', 'lego'), ('bricksandminifigsanaheim', 'bricksandminifigsanaheim')], max_length=200),
        ),
    ]
